---
version: 2
models:
- name: "model_Generalize_sp_generalize_us_states"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__Generalize_sp"
  database: "andre_dev"
  schema: "alteryx_spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mdf52yrn__Generalize_sp__generalize_us_states"
    tags:
    - "prophecy_temp"
