---
version: 2
models:
- name: "model_Distance_calculate_distance"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__Distance"
  database: "andre_dev"
  schema: "alteryx_spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mdetjzr4__Distance__calculate_distance"
    tags:
    - "prophecy_temp"
