---
version: 2
models:
- name: "model_Distance_calc_distance_kms"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__Distance"
  database: "andre_dev"
  schema: "alteryx_spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mdezq40d__Distance__calc_distance_kms"
    tags:
    - "prophecy_temp"
