---
version: 2
models:
- name: "model_FindNearest_find_nearest_centers"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__FindNearest"
  database: "andre_dev"
  schema: "alteryx_spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mdf1fjz8__FindNearest__find_nearest_centers"
    tags:
    - "prophecy_temp"
