---
version: 2
models:
- name: "model_PolyBuild_build_polyline"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__PolyBuild"
  database: "andre_dev"
  schema: "alteryx_spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mdf13x8p__PolyBuild__build_polyline"
    tags:
    - "prophecy_temp"
